var annotated_dup =
[
    [ "nlohmann", "namespacenlohmann.html", [
      [ "detail", "namespacenlohmann_1_1detail.html", [
        [ "container_input_adapter_factory_impl", "namespacenlohmann_1_1detail_1_1container__input__adapter__factory__impl.html", [
          [ "container_input_adapter_factory", "structnlohmann_1_1detail_1_1container__input__adapter__factory__impl_1_1container__input__adapter__factory.html", null ],
          [ "container_input_adapter_factory< ContainerType, void_t< decltype(begin(std::declval< ContainerType >()), end(std::declval< ContainerType >()))> >", "structnlohmann_1_1detail_1_1container__input__adapter__factory__impl_1_1container__input__adaptec6d36799bbab06a12576748f72ebcf00.html", "structnlohmann_1_1detail_1_1container__input__adapter__factory__impl_1_1container__input__adaptec6d36799bbab06a12576748f72ebcf00" ]
        ] ],
        [ "dtoa_impl", "namespacenlohmann_1_1detail_1_1dtoa__impl.html", [
          [ "boundaries", "structnlohmann_1_1detail_1_1dtoa__impl_1_1boundaries.html", "structnlohmann_1_1detail_1_1dtoa__impl_1_1boundaries" ],
          [ "cached_power", "structnlohmann_1_1detail_1_1dtoa__impl_1_1cached__power.html", "structnlohmann_1_1detail_1_1dtoa__impl_1_1cached__power" ],
          [ "diyfp", "structnlohmann_1_1detail_1_1dtoa__impl_1_1diyfp.html", "structnlohmann_1_1detail_1_1dtoa__impl_1_1diyfp" ]
        ] ],
        [ "utility_internal", "namespacenlohmann_1_1detail_1_1utility__internal.html", [
          [ "Extend", "structnlohmann_1_1detail_1_1utility__internal_1_1_extend.html", null ],
          [ "Extend< integer_sequence< T, Ints... >, SeqSize, 0 >", "structnlohmann_1_1detail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_intse4b696320406a0717efa9a961a507d9c.html", "structnlohmann_1_1detail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_intse4b696320406a0717efa9a961a507d9c" ],
          [ "Extend< integer_sequence< T, Ints... >, SeqSize, 1 >", "structnlohmann_1_1detail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_ints55b30810c0f772136f5c0a2221b86a09.html", "structnlohmann_1_1detail_1_1utility__internal_1_1_extend_3_01integer__sequence_3_01_t_00_01_ints55b30810c0f772136f5c0a2221b86a09" ],
          [ "Gen", "structnlohmann_1_1detail_1_1utility__internal_1_1_gen.html", "structnlohmann_1_1detail_1_1utility__internal_1_1_gen" ],
          [ "Gen< T, 0 >", "structnlohmann_1_1detail_1_1utility__internal_1_1_gen_3_01_t_00_010_01_4.html", "structnlohmann_1_1detail_1_1utility__internal_1_1_gen_3_01_t_00_010_01_4" ]
        ] ],
        [ "actual_object_comparator", "structnlohmann_1_1detail_1_1actual__object__comparator.html", "structnlohmann_1_1detail_1_1actual__object__comparator" ],
        [ "binary_reader", "classnlohmann_1_1detail_1_1binary__reader.html", "classnlohmann_1_1detail_1_1binary__reader" ],
        [ "binary_writer", "classnlohmann_1_1detail_1_1binary__writer.html", "classnlohmann_1_1detail_1_1binary__writer" ],
        [ "conjunction", "structnlohmann_1_1detail_1_1conjunction.html", null ],
        [ "conjunction< B >", "structnlohmann_1_1detail_1_1conjunction_3_01_b_01_4.html", null ],
        [ "conjunction< B, Bn... >", "structnlohmann_1_1detail_1_1conjunction_3_01_b_00_01_bn_8_8_8_01_4.html", null ],
        [ "detector", "structnlohmann_1_1detail_1_1detector.html", "structnlohmann_1_1detail_1_1detector" ],
        [ "detector< Default, void_t< Op< Args... > >, Op, Args... >", "structnlohmann_1_1detail_1_1detector_3_01_default_00_01void__t_3_01_op_3_01_args_8_8_8_01_4_01_4_00_01_op_00_01_args_8_8_8_01_4.html", "structnlohmann_1_1detail_1_1detector_3_01_default_00_01void__t_3_01_op_3_01_args_8_8_8_01_4_01_4_00_01_op_00_01_args_8_8_8_01_4" ],
        [ "exception", "classnlohmann_1_1detail_1_1exception.html", "classnlohmann_1_1detail_1_1exception" ],
        [ "external_constructor", "structnlohmann_1_1detail_1_1external__constructor.html", null ],
        [ "external_constructor< value_t::array >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1array_01_4.html", null ],
        [ "external_constructor< value_t::binary >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1binary_01_4.html", null ],
        [ "external_constructor< value_t::boolean >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1boolean_01_4.html", null ],
        [ "external_constructor< value_t::number_float >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__float_01_4.html", null ],
        [ "external_constructor< value_t::number_integer >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__integer_01_4.html", null ],
        [ "external_constructor< value_t::number_unsigned >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1number__unsigned_01_4.html", null ],
        [ "external_constructor< value_t::object >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1object_01_4.html", null ],
        [ "external_constructor< value_t::string >", "structnlohmann_1_1detail_1_1external__constructor_3_01value__t_1_1string_01_4.html", null ],
        [ "file_input_adapter", "classnlohmann_1_1detail_1_1file__input__adapter.html", "classnlohmann_1_1detail_1_1file__input__adapter" ],
        [ "from_json_fn", "structnlohmann_1_1detail_1_1from__json__fn.html", "structnlohmann_1_1detail_1_1from__json__fn" ],
        [ "has_from_json", "structnlohmann_1_1detail_1_1has__from__json.html", null ],
        [ "has_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__from__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01f77b5e367f2d5612b4276a155bf11896.html", "structnlohmann_1_1detail_1_1has__from__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01f77b5e367f2d5612b4276a155bf11896" ],
        [ "has_key_compare", "structnlohmann_1_1detail_1_1has__key__compare.html", null ],
        [ "has_non_default_from_json", "structnlohmann_1_1detail_1_1has__non__default__from__json.html", null ],
        [ "has_non_default_from_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__non__default__from__json_3_01_basic_json_type_00_01_t_00_01enab072547deb606b69b2d65cb910e223bb8.html", "structnlohmann_1_1detail_1_1has__non__default__from__json_3_01_basic_json_type_00_01_t_00_01enab072547deb606b69b2d65cb910e223bb8" ],
        [ "has_to_json", "structnlohmann_1_1detail_1_1has__to__json.html", null ],
        [ "has_to_json< BasicJsonType, T, enable_if_t< !is_basic_json< T >::value > >", "structnlohmann_1_1detail_1_1has__to__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01_96b7bbbe462cd4ff87697dab3bc993a77.html", "structnlohmann_1_1detail_1_1has__to__json_3_01_basic_json_type_00_01_t_00_01enable__if__t_3_01_96b7bbbe462cd4ff87697dab3bc993a77" ],
        [ "identity_tag", "structnlohmann_1_1detail_1_1identity__tag.html", null ],
        [ "input_stream_adapter", "classnlohmann_1_1detail_1_1input__stream__adapter.html", "classnlohmann_1_1detail_1_1input__stream__adapter" ],
        [ "integer_sequence", "structnlohmann_1_1detail_1_1integer__sequence.html", "structnlohmann_1_1detail_1_1integer__sequence" ],
        [ "internal_iterator", "structnlohmann_1_1detail_1_1internal__iterator.html", "structnlohmann_1_1detail_1_1internal__iterator" ],
        [ "invalid_iterator", "classnlohmann_1_1detail_1_1invalid__iterator.html", null ],
        [ "is_basic_json", "structnlohmann_1_1detail_1_1is__basic__json.html", null ],
        [ "is_basic_json< NLOHMANN_BASIC_JSON_TPL >", "structnlohmann_1_1detail_1_1is__basic__json_3_01_n_l_o_h_m_a_n_n___b_a_s_i_c___j_s_o_n___t_p_l_01_4.html", null ],
        [ "is_basic_json_context", "structnlohmann_1_1detail_1_1is__basic__json__context.html", null ],
        [ "is_comparable", "structnlohmann_1_1detail_1_1is__comparable.html", null ],
        [ "is_comparable< Compare, A, B, void_t< decltype(std::declval< Compare >()(std::declval< A >(), std::declval< B >())), decltype(std::declval< Compare >()(std::declval< B >(), std::declval< A >())) > >", "structnlohmann_1_1detail_1_1is__comparable_3_01_compare_00_01_a_00_01_b_00_01void__t_3_01decltypb2ae3852a526513ce424359684495c61.html", null ],
        [ "is_compatible_array_type", "structnlohmann_1_1detail_1_1is__compatible__array__type.html", null ],
        [ "is_compatible_array_type_impl", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl.html", null ],
        [ "is_compatible_array_type_impl< BasicJsonType, CompatibleArrayType, enable_if_t< is_detected< iterator_t, CompatibleArrayType >::value &&is_iterator_traits< iterator_traits< detected_t< iterator_t, CompatibleArrayType > > >::value &&!std::is_same< CompatibleArrayType, detected_t< range_value_t, CompatibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__compatible__array__type__impl_3_01_basic_json_type_00_01_compati4915acc171fa5fb7ebfebe0b9b6c0be2.html", null ],
        [ "is_compatible_integer_type", "structnlohmann_1_1detail_1_1is__compatible__integer__type.html", null ],
        [ "is_compatible_integer_type_impl", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl.html", null ],
        [ "is_compatible_integer_type_impl< RealIntegerType, CompatibleNumberIntegerType, enable_if_t< std::is_integral< RealIntegerType >::value &&std::is_integral< CompatibleNumberIntegerType >::value &&!std::is_same< bool, CompatibleNumberIntegerType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01_real_integer_type_00_01_combbf637f45e4984de1d118b9d7a65e604.html", "structnlohmann_1_1detail_1_1is__compatible__integer__type__impl_3_01_real_integer_type_00_01_combbf637f45e4984de1d118b9d7a65e604" ],
        [ "is_compatible_object_type", "structnlohmann_1_1detail_1_1is__compatible__object__type.html", null ],
        [ "is_compatible_object_type_impl", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl.html", null ],
        [ "is_compatible_object_type_impl< BasicJsonType, CompatibleObjectType, enable_if_t< is_detected< mapped_type_t, CompatibleObjectType >::value &&is_detected< key_type_t, CompatibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01_basic_json_type_00_01_compat5b5eeaa8fc54c99a69d765462ac539f5.html", "structnlohmann_1_1detail_1_1is__compatible__object__type__impl_3_01_basic_json_type_00_01_compat5b5eeaa8fc54c99a69d765462ac539f5" ],
        [ "is_compatible_string_type", "structnlohmann_1_1detail_1_1is__compatible__string__type.html", null ],
        [ "is_compatible_type", "structnlohmann_1_1detail_1_1is__compatible__type.html", null ],
        [ "is_compatible_type_impl", "structnlohmann_1_1detail_1_1is__compatible__type__impl.html", null ],
        [ "is_compatible_type_impl< BasicJsonType, CompatibleType, enable_if_t< is_complete_type< CompatibleType >::value > >", "structnlohmann_1_1detail_1_1is__compatible__type__impl_3_01_basic_json_type_00_01_compatible_typ632bee7ec037fc0233f1bbe9dd7d8874.html", null ],
        [ "is_complete_type", "structnlohmann_1_1detail_1_1is__complete__type.html", null ],
        [ "is_complete_type< T, decltype(void(sizeof(T)))>", "structnlohmann_1_1detail_1_1is__complete__type_3_01_t_00_01decltype_07void_07sizeof_07_t_08_08_08_4.html", null ],
        [ "is_constructible", "structnlohmann_1_1detail_1_1is__constructible.html", null ],
        [ "is_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "is_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "is_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "is_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "is_constructible_array_type", "structnlohmann_1_1detail_1_1is__constructible__array__type.html", null ],
        [ "is_constructible_array_type_impl", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl.html", null ],
        [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< !std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value &&!is_compatible_string_type< BasicJsonType, ConstructibleArrayType >::value &&is_default_constructible< ConstructibleArrayType >::value &&(std::is_move_assignable< ConstructibleArrayType >::value||std::is_copy_assignable< ConstructibleArrayType >::value) &&is_detected< iterator_t, ConstructibleArrayType >::value &&is_iterator_traits< iterator_traits< detected_t< iterator_t, ConstructibleArrayType > > >::value &&is_detected< range_value_t, ConstructibleArrayType >::value &&!std::is_same< ConstructibleArrayType, detected_t< range_value_t, ConstructibleArrayType > >::value &&is_complete_type< detected_t< range_value_t, ConstructibleArrayType > >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_consfd50d3f425260e9ce79880865c24c070.html", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_consfd50d3f425260e9ce79880865c24c070" ],
        [ "is_constructible_array_type_impl< BasicJsonType, ConstructibleArrayType, enable_if_t< std::is_same< ConstructibleArrayType, typename BasicJsonType::value_type >::value > >", "structnlohmann_1_1detail_1_1is__constructible__array__type__impl_3_01_basic_json_type_00_01_cons8cf88e17d5eaa68665a8fb4b97604b0e.html", null ],
        [ "is_constructible_object_type", "structnlohmann_1_1detail_1_1is__constructible__object__type.html", null ],
        [ "is_constructible_object_type_impl", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl.html", null ],
        [ "is_constructible_object_type_impl< BasicJsonType, ConstructibleObjectType, enable_if_t< is_detected< mapped_type_t, ConstructibleObjectType >::value &&is_detected< key_type_t, ConstructibleObjectType >::value > >", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl_3_01_basic_json_type_00_01_con1038de539babd212ea0aef1cc5752545.html", "structnlohmann_1_1detail_1_1is__constructible__object__type__impl_3_01_basic_json_type_00_01_con1038de539babd212ea0aef1cc5752545" ],
        [ "is_constructible_string_type", "structnlohmann_1_1detail_1_1is__constructible__string__type.html", "structnlohmann_1_1detail_1_1is__constructible__string__type" ],
        [ "is_constructible_tuple", "structnlohmann_1_1detail_1_1is__constructible__tuple.html", null ],
        [ "is_constructible_tuple< T1, std::tuple< Args... > >", "structnlohmann_1_1detail_1_1is__constructible__tuple_3_01_t1_00_01std_1_1tuple_3_01_args_8_8_8_01_4_01_4.html", null ],
        [ "is_default_constructible", "structnlohmann_1_1detail_1_1is__default__constructible.html", null ],
        [ "is_default_constructible< const std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "is_default_constructible< const std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01const_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "is_default_constructible< std::pair< T1, T2 > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1pair_3_01_t1_00_01_t2_01_4_01_4.html", null ],
        [ "is_default_constructible< std::tuple< Ts... > >", "structnlohmann_1_1detail_1_1is__default__constructible_3_01std_1_1tuple_3_01_ts_8_8_8_01_4_01_4.html", null ],
        [ "is_detected_lazy", "structnlohmann_1_1detail_1_1is__detected__lazy.html", null ],
        [ "is_getable", "structnlohmann_1_1detail_1_1is__getable.html", null ],
        [ "is_iterator_of_multibyte", "structnlohmann_1_1detail_1_1is__iterator__of__multibyte.html", "structnlohmann_1_1detail_1_1is__iterator__of__multibyte" ],
        [ "is_iterator_traits", "structnlohmann_1_1detail_1_1is__iterator__traits.html", null ],
        [ "is_iterator_traits< iterator_traits< T > >", "structnlohmann_1_1detail_1_1is__iterator__traits_3_01iterator__traits_3_01_t_01_4_01_4.html", null ],
        [ "is_json_iterator_of", "structnlohmann_1_1detail_1_1is__json__iterator__of.html", null ],
        [ "is_json_iterator_of< BasicJsonType, typename BasicJsonType::const_iterator >", "structnlohmann_1_1detail_1_1is__json__iterator__of_3_01_basic_json_type_00_01typename_01_basic_jc41a391b8ae8087564ffc6f880172795.html", null ],
        [ "is_json_iterator_of< BasicJsonType, typename BasicJsonType::iterator >", "structnlohmann_1_1detail_1_1is__json__iterator__of_3_01_basic_json_type_00_01typename_01_basic_json_type_1_1iterator_01_4.html", null ],
        [ "is_json_ref", "structnlohmann_1_1detail_1_1is__json__ref.html", null ],
        [ "is_json_ref< json_ref< T > >", "structnlohmann_1_1detail_1_1is__json__ref_3_01json__ref_3_01_t_01_4_01_4.html", null ],
        [ "is_ordered_map", "structnlohmann_1_1detail_1_1is__ordered__map.html", "structnlohmann_1_1detail_1_1is__ordered__map" ],
        [ "is_range", "structnlohmann_1_1detail_1_1is__range.html", null ],
        [ "is_sax", "structnlohmann_1_1detail_1_1is__sax.html", null ],
        [ "is_sax_static_asserts", "structnlohmann_1_1detail_1_1is__sax__static__asserts.html", null ],
        [ "is_specialization_of", "structnlohmann_1_1detail_1_1is__specialization__of.html", null ],
        [ "is_specialization_of< Primary, Primary< Args... > >", "structnlohmann_1_1detail_1_1is__specialization__of_3_01_primary_00_01_primary_3_01_args_8_8_8_01_4_01_4.html", null ],
        [ "iter_impl", "classnlohmann_1_1detail_1_1iter__impl.html", "classnlohmann_1_1detail_1_1iter__impl" ],
        [ "iteration_proxy", "classnlohmann_1_1detail_1_1iteration__proxy.html", "classnlohmann_1_1detail_1_1iteration__proxy" ],
        [ "iteration_proxy_value", "classnlohmann_1_1detail_1_1iteration__proxy__value.html", "classnlohmann_1_1detail_1_1iteration__proxy__value" ],
        [ "iterator_input_adapter", "classnlohmann_1_1detail_1_1iterator__input__adapter.html", "classnlohmann_1_1detail_1_1iterator__input__adapter" ],
        [ "iterator_input_adapter_factory", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory.html", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory" ],
        [ "iterator_input_adapter_factory< IteratorType, enable_if_t< is_iterator_of_multibyte< IteratorType >::value > >", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory_3_01_iterator_type_00_01enable__ifdbe9caa11c2ca51101ba1bbd1184c22c.html", "structnlohmann_1_1detail_1_1iterator__input__adapter__factory_3_01_iterator_type_00_01enable__ifdbe9caa11c2ca51101ba1bbd1184c22c" ],
        [ "iterator_traits", "structnlohmann_1_1detail_1_1iterator__traits.html", null ],
        [ "iterator_traits< T *, enable_if_t< std::is_object< T >::value > >", "structnlohmann_1_1detail_1_1iterator__traits_3_01_t_01_5_00_01enable__if__t_3_01std_1_1is__objec8d960665487688165530972cda4f1bea.html", "structnlohmann_1_1detail_1_1iterator__traits_3_01_t_01_5_00_01enable__if__t_3_01std_1_1is__objec8d960665487688165530972cda4f1bea" ],
        [ "iterator_traits< T, enable_if_t< !std::is_pointer< T >::value > >", "structnlohmann_1_1detail_1_1iterator__traits_3_01_t_00_01enable__if__t_3_01_9std_1_1is__pointer_3_01_t_01_4_1_1value_01_4_01_4.html", null ],
        [ "iterator_types", "structnlohmann_1_1detail_1_1iterator__types.html", null ],
        [ "iterator_types< It, void_t< typename It::difference_type, typename It::value_type, typename It::pointer, typename It::reference, typename It::iterator_category > >", "structnlohmann_1_1detail_1_1iterator__types_3_01_it_00_01void__t_3_01typename_01_it_1_1differenc4a413e9bd546446175f10f15c5631361.html", "structnlohmann_1_1detail_1_1iterator__types_3_01_it_00_01void__t_3_01typename_01_it_1_1differenc4a413e9bd546446175f10f15c5631361" ],
        [ "json_ref", "classnlohmann_1_1detail_1_1json__ref.html", "classnlohmann_1_1detail_1_1json__ref" ],
        [ "json_reverse_iterator", "classnlohmann_1_1detail_1_1json__reverse__iterator.html", "classnlohmann_1_1detail_1_1json__reverse__iterator" ],
        [ "json_sax_acceptor", "classnlohmann_1_1detail_1_1json__sax__acceptor.html", "classnlohmann_1_1detail_1_1json__sax__acceptor" ],
        [ "json_sax_dom_callback_parser", "classnlohmann_1_1detail_1_1json__sax__dom__callback__parser.html", "classnlohmann_1_1detail_1_1json__sax__dom__callback__parser" ],
        [ "json_sax_dom_parser", "classnlohmann_1_1detail_1_1json__sax__dom__parser.html", "classnlohmann_1_1detail_1_1json__sax__dom__parser" ],
        [ "lexer", "classnlohmann_1_1detail_1_1lexer.html", "classnlohmann_1_1detail_1_1lexer" ],
        [ "lexer_base", "classnlohmann_1_1detail_1_1lexer__base.html", "classnlohmann_1_1detail_1_1lexer__base" ],
        [ "make_void", "structnlohmann_1_1detail_1_1make__void.html", "structnlohmann_1_1detail_1_1make__void" ],
        [ "negation", "structnlohmann_1_1detail_1_1negation.html", null ],
        [ "nonesuch", "structnlohmann_1_1detail_1_1nonesuch.html", "structnlohmann_1_1detail_1_1nonesuch" ],
        [ "other_error", "classnlohmann_1_1detail_1_1other__error.html", null ],
        [ "out_of_range", "classnlohmann_1_1detail_1_1out__of__range.html", null ],
        [ "output_adapter", "classnlohmann_1_1detail_1_1output__adapter.html", "classnlohmann_1_1detail_1_1output__adapter" ],
        [ "output_adapter_protocol", "structnlohmann_1_1detail_1_1output__adapter__protocol.html", "structnlohmann_1_1detail_1_1output__adapter__protocol" ],
        [ "output_stream_adapter", "classnlohmann_1_1detail_1_1output__stream__adapter.html", "classnlohmann_1_1detail_1_1output__stream__adapter" ],
        [ "output_string_adapter", "classnlohmann_1_1detail_1_1output__string__adapter.html", "classnlohmann_1_1detail_1_1output__string__adapter" ],
        [ "output_vector_adapter", "classnlohmann_1_1detail_1_1output__vector__adapter.html", "classnlohmann_1_1detail_1_1output__vector__adapter" ],
        [ "parse_error", "classnlohmann_1_1detail_1_1parse__error.html", "classnlohmann_1_1detail_1_1parse__error" ],
        [ "parser", "classnlohmann_1_1detail_1_1parser.html", "classnlohmann_1_1detail_1_1parser" ],
        [ "position_t", "structnlohmann_1_1detail_1_1position__t.html", "structnlohmann_1_1detail_1_1position__t" ],
        [ "primitive_iterator_t", "classnlohmann_1_1detail_1_1primitive__iterator__t.html", "classnlohmann_1_1detail_1_1primitive__iterator__t" ],
        [ "priority_tag", "structnlohmann_1_1detail_1_1priority__tag.html", null ],
        [ "priority_tag< 0 >", "structnlohmann_1_1detail_1_1priority__tag_3_010_01_4.html", null ],
        [ "serializer", "classnlohmann_1_1detail_1_1serializer.html", "classnlohmann_1_1detail_1_1serializer" ],
        [ "span_input_adapter", "classnlohmann_1_1detail_1_1span__input__adapter.html", "classnlohmann_1_1detail_1_1span__input__adapter" ],
        [ "static_const", "structnlohmann_1_1detail_1_1static__const.html", null ],
        [ "to_json_fn", "structnlohmann_1_1detail_1_1to__json__fn.html", "structnlohmann_1_1detail_1_1to__json__fn" ],
        [ "type_error", "classnlohmann_1_1detail_1_1type__error.html", null ],
        [ "wide_string_input_adapter", "classnlohmann_1_1detail_1_1wide__string__input__adapter.html", "classnlohmann_1_1detail_1_1wide__string__input__adapter" ],
        [ "wide_string_input_helper", "structnlohmann_1_1detail_1_1wide__string__input__helper.html", null ],
        [ "wide_string_input_helper< BaseInputAdapter, 2 >", "structnlohmann_1_1detail_1_1wide__string__input__helper_3_01_base_input_adapter_00_012_01_4.html", null ],
        [ "wide_string_input_helper< BaseInputAdapter, 4 >", "structnlohmann_1_1detail_1_1wide__string__input__helper_3_01_base_input_adapter_00_014_01_4.html", null ]
      ] ],
      [ "adl_serializer", "structnlohmann_1_1adl__serializer.html", null ],
      [ "basic_json", "classnlohmann_1_1basic__json.html", "classnlohmann_1_1basic__json" ],
      [ "byte_container_with_subtype", "classnlohmann_1_1byte__container__with__subtype.html", "classnlohmann_1_1byte__container__with__subtype" ],
      [ "json_pointer", "classnlohmann_1_1json__pointer.html", "classnlohmann_1_1json__pointer" ],
      [ "json_sax", "structnlohmann_1_1json__sax.html", "structnlohmann_1_1json__sax" ],
      [ "ordered_map", "structnlohmann_1_1ordered__map.html", "structnlohmann_1_1ordered__map" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< nlohmann::NLOHMANN_BASIC_JSON_TPL >", "structstd_1_1hash_3_01nlohmann_1_1_n_l_o_h_m_a_n_n___b_a_s_i_c___j_s_o_n___t_p_l_01_4.html", "structstd_1_1hash_3_01nlohmann_1_1_n_l_o_h_m_a_n_n___b_a_s_i_c___j_s_o_n___t_p_l_01_4" ],
      [ "less< ::nlohmann::detail::value_t >", "structstd_1_1less_3_01_1_1nlohmann_1_1detail_1_1value__t_01_4.html", "structstd_1_1less_3_01_1_1nlohmann_1_1detail_1_1value__t_01_4" ],
      [ "tuple_element< N, ::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__element_3_01_n_00_01_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01_iterator_type_01_4_01_4.html", "classstd_1_1tuple__element_3_01_n_00_01_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01_iterator_type_01_4_01_4" ],
      [ "tuple_size<::nlohmann::detail::iteration_proxy_value< IteratorType > >", "classstd_1_1tuple__size_3_1_1nlohmann_1_1detail_1_1iteration__proxy__value_3_01_iterator_type_01_4_01_4.html", null ]
    ] ],
    [ "tigl", "namespacetigl.html", [
      [ "internal", "namespacetigl_1_1internal.html", [
        [ "Shader", "classtigl_1_1internal_1_1_shader.html", "classtigl_1_1internal_1_1_shader" ]
      ] ],
      [ "ShaderImpl", "classtigl_1_1_shader_impl.html", "classtigl_1_1_shader_impl" ],
      [ "VBO", "classtigl_1_1_v_b_o.html", "classtigl_1_1_v_b_o" ],
      [ "Vertex", "structtigl_1_1_vertex.html", "structtigl_1_1_vertex" ]
    ] ],
    [ "FpsCam", "class_fps_cam.html", "class_fps_cam" ],
    [ "GameObject", "class_game_object.html", "class_game_object" ],
    [ "GameObjectFactory", "class_game_object_factory.html", null ],
    [ "MovableGameObject", "class_movable_game_object.html", "class_movable_game_object" ],
    [ "ObjModel", "class_obj_model.html", "class_obj_model" ],
    [ "SceneFactory", "class_scene_factory.html", null ],
    [ "SceneManager", "class_scene_manager.html", "class_scene_manager" ],
    [ "SpinningGameObject", "class_spinning_game_object.html", "class_spinning_game_object" ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", "structstbi__io__callbacks" ],
    [ "Texture", "class_texture.html", "class_texture" ],
    [ "UUIDGenerator", "class_u_u_i_d_generator.html", "class_u_u_i_d_generator" ],
    [ "UUIDGeneratorSingleton", "class_u_u_i_d_generator_singleton.html", "class_u_u_i_d_generator_singleton" ],
    [ "WindowSingleton", "class_window_singleton.html", "class_window_singleton" ]
];